// <auto-generated/>
using System;
using System.Reflection;
using System.Resources;

[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("stef")]
[assembly: AssemblyProductAttribute("WPF Converters")]
[assembly: AssemblyCopyrightAttribute("© Copyright. stefv")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: CLSCompliantAttribute(true)]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0")]
